package com.tool.Model;

import com.tool.Model.base.BaseAdministrator;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Administrator extends BaseAdministrator<Administrator> {
	public static final Administrator dao = new Administrator().dao();
}
