package com.tool.Model;

import com.tool.Model.base.BaseAdviser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Adviser extends BaseAdviser<Adviser> {
	public static final Adviser dao = new Adviser().dao();
}
