package com.tool.Model;

import com.tool.Model.base.BaseCompetition;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Competition extends BaseCompetition<Competition> {
	public static final Competition dao = new Competition().dao();
}
