package com.tool.Model;

import com.tool.Model.base.BaseInformationFile;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class InformationFile extends BaseInformationFile<InformationFile> {
	public static final InformationFile dao = new InformationFile().dao();
}
