package com.tool.Model;

import com.tool.Model.base.BaseInvite;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Invite extends BaseInvite<Invite> {
	public static final Invite dao = new Invite().dao();
}
