package com.tool.Model;

import com.tool.Model.base.BaseMembersInformation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MembersInformation extends BaseMembersInformation<MembersInformation> {
	public static final MembersInformation dao = new MembersInformation().dao();
}
