package com.tool.Model;

import com.tool.Model.base.BaseParticipant;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Participant extends BaseParticipant<Participant> {
	public static final Participant dao = new Participant().dao();
}
