package com.tool.Model;

import com.tool.Model.base.BaseProject;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Project extends BaseProject<Project> {
	public static final Project dao = new Project().dao();
}
