package com.tool.Model;

import com.tool.Model.base.BaseProjectFile;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProjectFile extends BaseProjectFile<ProjectFile> {
	public static final ProjectFile dao = new ProjectFile().dao();
}
