package com.tool.Model;

import com.tool.Model.base.BaseTeam;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Team extends BaseTeam<Team> {
	public static final Team dao = new Team().dao();
}
