package com.tool.Model;

import com.tool.Model.base.BaseTeamMember;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TeamMember extends BaseTeamMember<TeamMember> {
	public static final TeamMember dao = new TeamMember().dao();
}
