package com.tool.Model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMembersInformation<M extends BaseMembersInformation<M>> extends Model<M> implements IBean {

	public M setInformationId(java.lang.Integer informationId) {
		set("Information_id", informationId);
		return (M)this;
	}
	
	public java.lang.Integer getInformationId() {
		return getInt("Information_id");
	}

	public M setAdministratorId(java.lang.Integer administratorId) {
		set("Administrator_id", administratorId);
		return (M)this;
	}
	
	public java.lang.Integer getAdministratorId() {
		return getInt("Administrator_id");
	}

	public M setMembersSchool(java.lang.String membersSchool) {
		set("Members_school", membersSchool);
		return (M)this;
	}
	
	public java.lang.String getMembersSchool() {
		return getStr("Members_school");
	}

	public M setMembersId(java.lang.Integer membersId) {
		set("Members_id", membersId);
		return (M)this;
	}
	
	public java.lang.Integer getMembersId() {
		return getInt("Members_id");
	}

	public M setMembersName(java.lang.String membersName) {
		set("Members_name", membersName);
		return (M)this;
	}
	
	public java.lang.String getMembersName() {
		return getStr("Members_name");
	}

	public M setMembersCategory(java.lang.String membersCategory) {
		set("Members_category", membersCategory);
		return (M)this;
	}
	
	public java.lang.String getMembersCategory() {
		return getStr("Members_category");
	}

	public M setMembersSex(java.lang.String membersSex) {
		set("Members_sex", membersSex);
		return (M)this;
	}
	
	public java.lang.String getMembersSex() {
		return getStr("Members_sex");
	}

	public M setMembersPosition(java.lang.String membersPosition) {
		set("Members_position", membersPosition);
		return (M)this;
	}
	
	public java.lang.String getMembersPosition() {
		return getStr("Members_position");
	}

	public M setMembersTel(java.lang.String membersTel) {
		set("Members_tel", membersTel);
		return (M)this;
	}
	
	public java.lang.String getMembersTel() {
		return getStr("Members_tel");
	}

	public M setTrafficWay(java.lang.String trafficWay) {
		set("Traffic_way", trafficWay);
		return (M)this;
	}
	
	public java.lang.String getTrafficWay() {
		return getStr("Traffic_way");
	}

	public M setTrafficTime(java.util.Date trafficTime) {
		set("Traffic_time", trafficTime);
		return (M)this;
	}
	
	public java.util.Date getTrafficTime() {
		return get("Traffic_time");
	}

	public M setTrafficNum(java.lang.String trafficNum) {
		set("Traffic_num", trafficNum);
		return (M)this;
	}
	
	public java.lang.String getTrafficNum() {
		return getStr("Traffic_num");
	}

	public M setTrafficArriveplace(java.lang.String trafficArriveplace) {
		set("Traffic_arriveplace", trafficArriveplace);
		return (M)this;
	}
	
	public java.lang.String getTrafficArriveplace() {
		return getStr("Traffic_arriveplace");
	}

	public M setTrafficArrivetime(java.util.Date trafficArrivetime) {
		set("Traffic_arrivetime", trafficArrivetime);
		return (M)this;
	}
	
	public java.util.Date getTrafficArrivetime() {
		return get("Traffic_arrivetime");
	}

	public M setTrafficLeaveplace(java.lang.String trafficLeaveplace) {
		set("Traffic_leaveplace", trafficLeaveplace);
		return (M)this;
	}
	
	public java.lang.String getTrafficLeaveplace() {
		return getStr("Traffic_leaveplace");
	}

	public M setTrafficLeavetime(java.util.Date trafficLeavetime) {
		set("Traffic_leavetime", trafficLeavetime);
		return (M)this;
	}
	
	public java.util.Date getTrafficLeavetime() {
		return get("Traffic_leavetime");
	}

	public M setAccommodationDays(java.lang.Integer accommodationDays) {
		set("Accommodation_days", accommodationDays);
		return (M)this;
	}
	
	public java.lang.Integer getAccommodationDays() {
		return getInt("Accommodation_days");
	}

	public M setAccommodationTime(java.util.Date accommodationTime) {
		set("Accommodation_time", accommodationTime);
		return (M)this;
	}
	
	public java.util.Date getAccommodationTime() {
		return get("Accommodation_time");
	}

	public M setAccommodationLeave(java.util.Date accommodationLeave) {
		set("Accommodation_leave", accommodationLeave);
		return (M)this;
	}
	
	public java.util.Date getAccommodationLeave() {
		return get("Accommodation_leave");
	}

	public M setAccommodationType(java.lang.String accommodationType) {
		set("Accommodation_type", accommodationType);
		return (M)this;
	}
	
	public java.lang.String getAccommodationType() {
		return getStr("Accommodation_type");
	}

	public M setAccommodationNeed(java.lang.String accommodationNeed) {
		set("Accommodation_need", accommodationNeed);
		return (M)this;
	}
	
	public java.lang.String getAccommodationNeed() {
		return getStr("Accommodation_need");
	}

	public M setInformationRemarks(java.lang.String informationRemarks) {
		set("Information_remarks", informationRemarks);
		return (M)this;
	}
	
	public java.lang.String getInformationRemarks() {
		return getStr("Information_remarks");
	}

}
