package com.tool.Model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseInformationFile<M extends BaseInformationFile<M>> extends Model<M> implements IBean {

	public M setFileId(java.lang.Integer fileId) {
		set("File_id", fileId);
		return (M)this;
	}
	
	public java.lang.Integer getFileId() {
		return getInt("File_id");
	}

	public M setFileName(java.lang.String fileName) {
		set("File_name", fileName);
		return (M)this;
	}
	
	public java.lang.String getFileName() {
		return getStr("File_name");
	}

}
