package com.tool.Model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseParticipant<M extends BaseParticipant<M>> extends Model<M> implements IBean {

	public M setParticipantId(java.lang.Integer participantId) {
		set("Participant_id", participantId);
		return (M)this;
	}
	
	public java.lang.Integer getParticipantId() {
		return getInt("Participant_id");
	}

	public M setParticipantImage(java.lang.String participantImage) {
		set("Participant_image", participantImage);
		return (M)this;
	}
	
	public java.lang.String getParticipantImage() {
		return getStr("Participant_image");
	}

	public M setParticipantName(java.lang.String participantName) {
		set("Participant_name", participantName);
		return (M)this;
	}
	
	public java.lang.String getParticipantName() {
		return getStr("Participant_name");
	}

	public M setParticipantIdnumber(java.lang.String participantIdnumber) {
		set("Participant_IDNumber", participantIdnumber);
		return (M)this;
	}
	
	public java.lang.String getParticipantIdnumber() {
		return getStr("Participant_IDNumber");
	}

	public M setParticipantSex(java.lang.String participantSex) {
		set("Participant_sex", participantSex);
		return (M)this;
	}
	
	public java.lang.String getParticipantSex() {
		return getStr("Participant_sex");
	}

	public M setParticipantSchool(java.lang.String participantSchool) {
		set("Participant_school", participantSchool);
		return (M)this;
	}
	
	public java.lang.String getParticipantSchool() {
		return getStr("Participant_school");
	}

	public M setParticipantPhone(java.lang.String participantPhone) {
		set("Participant_phone", participantPhone);
		return (M)this;
	}
	
	public java.lang.String getParticipantPhone() {
		return getStr("Participant_phone");
	}

	public M setParticipantMail(java.lang.String participantMail) {
		set("Participant_mail", participantMail);
		return (M)this;
	}
	
	public java.lang.String getParticipantMail() {
		return getStr("Participant_mail");
	}

	public M setParticipantAddress(java.lang.String participantAddress) {
		set("Participant_address", participantAddress);
		return (M)this;
	}
	
	public java.lang.String getParticipantAddress() {
		return getStr("Participant_address");
	}

	public M setParticipantAccount(java.lang.String participantAccount) {
		set("Participant_account", participantAccount);
		return (M)this;
	}
	
	public java.lang.String getParticipantAccount() {
		return getStr("Participant_account");
	}

	public M setParticipantPassword(java.lang.String participantPassword) {
		set("Participant_password", participantPassword);
		return (M)this;
	}
	
	public java.lang.String getParticipantPassword() {
		return getStr("Participant_password");
	}

}
