package com.tool.Model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTeam<M extends BaseTeam<M>> extends Model<M> implements IBean {

	public M setTeamId(java.lang.Integer teamId) {
		set("Team_id", teamId);
		return (M)this;
	}
	
	public java.lang.Integer getTeamId() {
		return getInt("Team_id");
	}

	public M setParticipantId(java.lang.Integer participantId) {
		set("Participant_id", participantId);
		return (M)this;
	}
	
	public java.lang.Integer getParticipantId() {
		return getInt("Participant_id");
	}

	public M setTeamName(java.lang.String teamName) {
		set("Team_name", teamName);
		return (M)this;
	}
	
	public java.lang.String getTeamName() {
		return getStr("Team_name");
	}

	public M setTeamSettime(java.util.Date teamSettime) {
		set("Team_setTime", teamSettime);
		return (M)this;
	}
	
	public java.util.Date getTeamSettime() {
		return get("Team_setTime");
	}

}
