package com.tool.Model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTeamMember<M extends BaseTeamMember<M>> extends Model<M> implements IBean {

	public M setMemberId(java.lang.Integer memberId) {
		set("Member_id", memberId);
		return (M)this;
	}
	
	public java.lang.Integer getMemberId() {
		return getInt("Member_id");
	}

	public M setTeamId(java.lang.Integer teamId) {
		set("Team_id", teamId);
		return (M)this;
	}
	
	public java.lang.Integer getTeamId() {
		return getInt("Team_id");
	}

	public M setMemberType(java.lang.Integer memberType) {
		set("Member_type", memberType);
		return (M)this;
	}
	
	public java.lang.Integer getMemberType() {
		return getInt("Member_type");
	}

	public M setMemberName(java.lang.String memberName) {
		set("Member_name", memberName);
		return (M)this;
	}
	
	public java.lang.String getMemberName() {
		return getStr("Member_name");
	}

	public M setMemberProfessional(java.lang.String memberProfessional) {
		set("Member_professional", memberProfessional);
		return (M)this;
	}
	
	public java.lang.String getMemberProfessional() {
		return getStr("Member_professional");
	}

	public M setMemberSchool(java.lang.String memberSchool) {
		set("Member_school", memberSchool);
		return (M)this;
	}
	
	public java.lang.String getMemberSchool() {
		return getStr("Member_school");
	}

	public M setMemberIdnumber(java.lang.String memberIdnumber) {
		set("Member_IDNumber", memberIdnumber);
		return (M)this;
	}
	
	public java.lang.String getMemberIdnumber() {
		return getStr("Member_IDNumber");
	}

	public M setMemberTel(java.lang.String memberTel) {
		set("Member_tel", memberTel);
		return (M)this;
	}
	
	public java.lang.String getMemberTel() {
		return getStr("Member_tel");
	}

	public M setMemberMail(java.lang.String memberMail) {
		set("Member_mail", memberMail);
		return (M)this;
	}
	
	public java.lang.String getMemberMail() {
		return getStr("Member_mail");
	}

	public M setMemberEnroltime(java.lang.String memberEnroltime) {
		set("Member_enrolTime", memberEnroltime);
		return (M)this;
	}
	
	public java.lang.String getMemberEnroltime() {
		return getStr("Member_enrolTime");
	}

}
